### ISSUE TITLE
Missing class: The type Initializer for 'KSPe.IO.Hierarchy 1' threw an exception error

### ISSUE THREAD

**Issue by egrochka** [net-lisias-ksp/KSPAPIExtensions#25]
Hi, @Lisias

I'm also getting the `Missing class: The type Initializer for 'KSPe.IO.Hierarchy 1' threw an exception` error when starting ksp.

I tried the other solutions found here but none of them worked for me.

Note: I'm not using windows, i run the game trough proton on manjaro linux.

[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/7897754/KSP.log)

**Comment by hendrack** [comment]
Long time no see :) 

Now that I have migrated to linux again, I don't think this is a proton bug, but rather mono, because I get this as well with the native linux version and latest Recall/MM/KSPApiExtension:

[EXC 14:11:08.302] Exception: Magic number is wrong: 542
	System.TermInfoReader.ReadHeader (System.Byte[] buffer, System.Int32& position) (at <9577ac7a62ef43179789031239ba8798>:0)
	System.TermInfoReader..ctor (System.String term, System.String filename) (at <9577ac7a62ef43179789031239ba8798>:0)
	System.TermInfoDriver..ctor (System.String term) (at <9577ac7a62ef43179789031239ba8798>:0)
	System.ConsoleDriver.CreateTermInfoDriver (System.String term) (at <9577ac7a62ef43179789031239ba8798>:0)
	System.ConsoleDriver..cctor () (at <9577ac7a62ef43179789031239ba8798>:0)
	Rethrow as TypeInitializationException: The type initializer for 'System.ConsoleDriver' threw an exception.
	System.Console.SetupStreams (System.Text.Encoding inputEncoding, System.Text.Encoding outputEncoding) (at <9577ac7a62ef43179789031239ba8798>:0)
	System.Console..cctor () (at <9577ac7a62ef43179789031239ba8798>:0)
	Rethrow as TypeInitializationException: The type initializer for 'System.Console' threw an exception.
	System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) (at <ef151b6abb5d474cb2c1cb8906a8b5a4>:0)
	System.Diagnostics.Process.Start () (at <ef151b6abb5d474cb2c1cb8906a8b5a4>:0)
	(wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
	KSPe.Multiplatform.Shell.command (System.String command, System.String commandline) (at <05f81ffbee73404ba435226cd87dcc0c>:0)
	KSPe.Multiplatform.FileSystem.Reparse_readlink (System.String path) (at <05f81ffbee73404ba435226cd87dcc0c>:0)
	KSPe.Multiplatform.FileSystem.ReparsePath (System.String path) (at <05f81ffbee73404ba435226cd87dcc0c>:0)
	KSPe.IO.Directory.RealPath (System.String path) (at <05f81ffbee73404ba435226cd87dcc0c>:0)
	KSPe.IO.Directory.Exists (System.String path) (at <05f81ffbee73404ba435226cd87dcc0c>:0)
	KSPe.IO.Path.EnsureTrailingSeparatorOnDir (System.String path, System.Boolean blindlyAppend) (at <05f81ffbee73404ba435226cd87dcc0c>:0)
	KSPe.IO.Path.Combine (System.String path1, System.String path2) (at <05f81ffbee73404ba435226cd87dcc0c>:0)
	KSPe.IO.Hierarchy..cctor () (at <05f81ffbee73404ba435226cd87dcc0c>:0)
	Rethrow as TypeInitializationException: The type initializer for 'KSPe.IO.Hierarchy' threw an exception.
	KSPe.Util.SystemTools+Assembly+Loader..ctor (System.String namespaceOverride, System.String[] subdirs) (at <05f81ffbee73404ba435226cd87dcc0c>:0)
	KSPe.UI.Startup.Awake () (at <47d41d569738492196e4d2b03803cdd0>:0)
	Rethrow as TypeInitializationException: The type initializer for 'KSPe.IO.Hierarchy`1' threw an exception.
	KSPe.IO.File`1+Data[T].FullPathName (System.Boolean createDirs, System.String fn, System.String[] fns) (at <05f81ffbee73404ba435226cd87dcc0c>:0)
	KSPe.IO.Data`1+ConfigNode[T].For (System.String name, System.String filename) (at <05f81ffbee73404ba435226cd87dcc0c>:0)
	ModuleManager.FilePathRepository..cctor () (at <60b0b7653af84cb3871e096a9317f5a6>:0)
	Rethrow as TypeInitializationException: The type initializer for 'ModuleManager.FilePathRepository' threw an exception.
	ModuleManager.MMPatchRunner+<>c__DisplayClass13_0.<Run>b__0 () (at <60b0b7653af84cb3871e096a9317f5a6>:0)
	ModuleManager.Threading.BackgroundTask+<>c__DisplayClass0_0.<Start>g__RunAction|0 () (at <60b0b7653af84cb3871e096a9317f5a6>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	KSPe.Util.Log.UnityLogDecorator:UnityEngine.ILogHandler.LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	KSPe.Util.Log.UnityLogger:logException(String, Exception)
	KSPe.Util.Log.Logger:error(Exception, String, Object[])
	ModuleManager.Logging.ModLogger:Exception(String, Exception)
	ModuleManager.<Run>d__13:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by Lisias** [comment]
@hendrack 

> Long time no see :)

Hi! :)




> Now that I have migrated to linux again, I don't think this is a proton bug, but rather mono, because I get this as well with the native linux version and latest Recall/MM/KSPApiExtension:
> 
> [EXC 14:11:08.302] Exception: Magic number is wrong: 542 System.TermInfoReader.ReadHeader (System.Byte[] buffer, System.Int32& position) (at <9577ac7a62ef43179789031239ba8798>:0) System.TermInfoReader..ctor (System.String term, System.String filename) (at <9577ac7a62ef43179789031239ba8798>:0) System.TermInfoDriver..ctor (System.String term) (at <9577ac7a62ef43179789031239ba8798>:0) System.ConsoleDriver.CreateTermInfoDriver (System.String term) (at <9577ac7a62ef43179789031239ba8798>:0) System.ConsoleDriver..cctor () (at 
<cut>

Geez!!! This one is a new! (googling, googling, googling… ah! found something!)

Try to set the following environment variable before running KSP:

```
export TERM=xterm
```

(change `xterm` to any other terminal you are using on your rig - `xterm` is a safe default value, nobody uses it but it's always available)

I think this is more a mishap no your `.profile` file (or perhaps the program launcher you are using) than anything else!

**Comment by hendrack** [comment]
Never had this issue with a lot of linux flavors in the past, but that environment variable did the trick.

**Comment by Lisias** [comment]
> Never had this issue with a lot of linux flavors in the past, but that environment variable did the trick.

Put that line in your `~./profile` file. This will fix the problem for everybody.

I think current maintainers are not used to the old X11 ways - and since even WayLand aims to be support X11 applications (Xwayland), this may be a mistake.

**Comment by Lisias** [comment]
Well, case closed! :)
