### ISSUE TITLE
TRACKING: ModuleManagerAddToModList() error on KSPe.*

### ISSUE THREAD

**Issue by 7ranceaddic7** [net-lisias-ksp/KSPAPIExtensions#5]
First-time I've seen this.
Dropping it here just for tracking at this point.

#### BEGIN MODULEMANAGER LOG ####

[LOG 10:10:03.514] Log started at 2020-08-09 10:10:03.514
[LOG 10:10:19.659] Calling KSPe.KSP.19.ModuleManagerSupport.ModuleManagerAddToModList()
[LOG 10:10:19.659] Calling KSPe.KSP.18.ModuleManagerSupport.ModuleManagerAddToModList()
[LOG 10:10:19.660] Calling KSPe.KSP.17.ModuleManagerSupport.ModuleManagerAddToModList()
[LOG 10:10:19.660] Calling KSPe.KSP.16.ModuleManagerSupport.ModuleManagerAddToModList()
[LOG 10:10:19.660] Calling KSPe.KSP.15.ModuleManagerSupport.ModuleManagerAddToModList()
[LOG 10:10:19.660] Calling KSPe.KSP.14.ModuleManagerSupport.ModuleManagerAddToModList()
[LOG 10:10:19.660] Calling KSPe.KSP.13.ModuleManagerSupport.ModuleManagerAddToModList()
[LOG 10:10:19.660] Calling KSPe.KSP.12.ModuleManagerSupport.ModuleManagerAddToModList()
[LOG 10:10:19.660] Calling KSPe.KSP.11.ModuleManagerSupport.ModuleManagerAddToModList()
[EXC 10:10:19.662] Add to mod list threw an exception in loading e09417c2-1c0d-4aae-bff2-d21af3713e55, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at System.Reflection.Emit.AssemblyBuilder.GetTypes (System.Boolean exportedOnly) [0x0012d] in <ad04dee02e7e4a85a1299c7ee81c79f6>:0 
  at System.Reflection.Assembly.GetTypes () [0x00000] in <ad04dee02e7e4a85a1299c7ee81c79f6>:0 
  at ModuleManager.ModListGenerator.GetAdditionalModsFromStaticMethods (ModuleManager.Logging.IBasicLogger logger) [0x00021] in <410b7909691747c78c895491c954d2a4>:0 
[LOG 10:10:19.663] Calling Kerbalism.MM40Injector.ModuleManagerAddToModList()
[LOG 10:10:19.669] Checking Cache
[LOG 10:10:20.926] SHA generated in 1.255s
[LOG 10:10:20.926]       SHA = 7B-E0-DC-77-6D-4B-5E-01-75-56-AE-4B-0F-9A-8C-42-6C-F6-44-86-A0-B5-5E-7E-41-68-43-9E-2B-6F-F0-CB
[LOG 10:10:21.531] Changes :
Added   : PatchManager/ActiveMMPatches/Smart_Parts_SM_MM_Prox4All.cfg
Added   : PatchManager/ActiveMMPatches/Smart_Parts_SM_MM_Radio4All.cfg
Added   : PatchManager/ActiveMMPatches/Smart_Parts_SM_MM_SmartSRB4All.cfg
Added   : __myLOCAL/TaerobeeSufrAttachParachute.cfg

[LOG 10:10:21.531] Cache SHA = 9A-39-AF-60-AB-E6-23-99-8E-A3-39-9F-59-7A-02-03-4A-15-C6-15-1C-6B-AF-D0-01-D8-EC-90-0B-F2-AE-3E
[LOG 10:10:21.531] useCache = False
[LOG 10:10:21.532] Pre patch init
[LOG 10:10:22.499] compiling list of loaded mods...
Mod DLLs found:

**Comment by Lisias** [comment]
Sounds like a dependency is not satisfied.

Since the loading started with 19, I'm assuming you are using KSP 1.9.0 or 1.9.1.

On this case, the borking must be happening on loading the KSP.UI, and on anything equal or bigger than 1.4.0 you need to install ClickThroughBlocker (and recently, ToolBar Control as CTB now depends on it).

Ideally this should be optional, but I didn't found the time (yet) to write an speculative loader for the KSP.UI (essentially, I should write an additional KSP.UI.1.4.0 to be used when no CTB is installed).

**Comment by Lisias** [comment]
On a side thought, the [INSTALL](https://github.com/net-lisias-ksp/KSPAPIExtensions/blob/mestre/INSTALL.md) instructions can be better written...

**Comment by Lisias** [comment]
Damn. Forgot to fix the INSTALL. Posponing it to the next revision

**Comment by Lisias** [comment]
The INSTALL was update to satisfy this issue on commit https://github.com/net-lisias-ksp/KSPAPIExtensions/commit/e1c0bd52d893a1b9e7aed5405df9d1b64b0928ea .

The commit https://github.com/net-lisias-ksp/KSPAPIExtensions/commit/3c740393ce47f52c50d78bf56b523edb6e91c930 also mitigates the problem (besides waiving features).

**Comment by Lisias** [comment]
On a side note, KSPe now checks if the CTB is installed and, when don't, shift for the KSP.UI.13 DLL where it is not a dependency.
